theme = "base16_transparent"


#Editor
[editor]
line-number = "relative"
mouse = false 
bufferline = "multiple"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false 

[editor.lsp]
display-messages = true


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
